# Generated by Django 5.2.5 on 2025-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedDatas', '0002_rename_destionationdesc_useruploads_destinationdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploads',
            name='destinationImg',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='user_upload/'),
        ),
    ]
