# Generated by Django 5.2.5 on 2025-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedDatas', '0003_alter_useruploads_destinationimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploads',
            name='destinationImg',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='user_data/'),
        ),
    ]
