# Generated by Django 5.2.5 on 2025-08-14 19:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=20)),
                ('placeDesc', tinymce.models.HTMLField()),
                ('placeImg', models.ImageField(default=None, max_length=250, null=True, upload_to='user_data/')),
            ],
        ),
    ]
