# Generated by Django 5.2.5 on 2025-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdata',
            name='placeDesc',
            field=models.TextField(),
        ),
    ]
