# Generated by Django 5.2.5 on 2025-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=20)),
                ('destinationImg', models.ImageField(default=None, max_length=250, null=True, upload_to='user_data/')),
                ('destionationDesc', models.TextField()),
            ],
        ),
    ]
