# Generated by Django 5.2.5 on 2025-08-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedDatas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploads',
            old_name='destionationDesc',
            new_name='destinationDesc',
        ),
    ]
